apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-mutate
  namespace: webhook-example
  labels:
    app: mutate-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutate-server
  template:
    metadata:
      labels:
        app: mutate-server
    spec:
      containers:
      - name: server
        image: alicek106/k8s-admission-controller-mutator:0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: flask 

        volumeMounts:
        - name: webhook-tls
          mountPath: /run/secrets/tls
          readOnly: true

      volumes:
      - name: webhook-tls
        secret:
          secretName: webhook-certs
---
apiVersion: v1
kind: Service
metadata:
  name: mutate-server-svc
  namespace: webhook-example
spec:
  selector:
    app: mutate-server
  ports:
    - port: 443
      targetPort: flask 
